---
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
    number_sections: false
    extra_dependencies: ["float"]
bibliography: ecol.bib
---

Weed communities in three cropping systems suitable for the Midwestern USA were studied from 2017 through 2020 to examine how crop diversification and the intensity of herbicide use affected weed community diversity, stand density, and aboveground mass. A baseline 2-year cropping system with corn (*Zea mays* L.) and soybean (*Glycine max* (L.) Merr.) grown in alternate years was diversified with cool-season crops, namely oat (*Avena sativa* L.), red clover (*Trifolium pratense* L.), and alfalfa (*Medicago sativa* L.) in 3-year and 4-year systems. Herbicide was not applied in the cool-season crops. Changing weed management regime from broadcast to banded application and interrow cultivation in corn and omitting herbicide in cool-season crops of the 3-year and 4-year rotations resulted in an overall reduction of herbicide a.i mass. The reduction in the mass of herbicide active ingredients was associated with increases in weed stand density, aboveground mass, and community diversity. Increased weed abundance under herbicide mass reduction was not associated with crop yield loss. In the cool-season crops phases of the 3-year and 4-year rotations, weed emergence was increased but weed growth was not, as compared with the warm-season crop environments. The dominance of aggressive weed species such as common waterhemp (*Amaranthus tuberculatus* (Moq ex DC) J.D. Sauer) and common lambsquarter (*Chenopodium album* L.) tended to be greater in corn and soybean phases of the rotations than in oat, red clover, and alfalfa.

