---
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
    number_sections: false
    extra_dependencies: ["float"]
    latex_engine: lualatex
    citation_package: natbib
bibliography: ecol.bib
natbiboptions: round
biblatexoptions:
  - sortcites = true
  - sorting = nyt
  - backend = biber
  - maxcitenames = 2
csl: apa-no-ampersand.csl
---


Diversification of cropping systems led to increased weed community aboveground mass and stand density, increased weed community diversity and species richness, and decreased weed community evenness. Increased weed abundance was not associated with reduced crop yield. Crop identity in the present experiment had the strongest influence on the response variables. This observation is consistent with previous studies in which crop identity showed the strongest influence on weed community characteristics [@legereDiversityAssemblyWeed2005; @smithAssemblyWeedCommunities2007]. The observation that crop yields were not correlated with increased weed aboveground mass suggests that low amounts of weed biomass can be tolerated, rather than the commonly desired weed-free condition [@zimdahlNeedHistoricalPerspective2012]. Tolerating greater weed abundance can create some risks of resurgence by formerly prevalent weed species or outbreak of highly adapted introduced species under favorable conditions [@mohlerWeedEvolutionCommunity2001]. Consequently, weed growth and weed community composition should be monitored frequently to keep weed infestations at tolerable levels and to detect risks for future seasons. As weeds develop resistance to herbicides, weed eradication is likely to be increasingly impractical for technical, financial, and environmental reasons [@brookesKeyEnvironmentalImpacts2013; @stewartWeedControlEnvironmental2011], making the monitoring of weed communities a critically important component of weed management.   

@ryanManagementFiltersSpecies2010 found that weeds growing in a preceding crop phase of a sequence affected the subsequent seedbank more strongly than the seedbank influenced the emerged weed flora; the investigators attributed this a filtering effect of crop management on weed seed production by mixed-species communities. The four years of data presented here did not reveal any weed species that might become aggressive in the presence of oat, red clover, and alfalfa. Following the critical period for weed control concepts described by @knezevicCriticalPeriodWeed2002, weed control measures were applied in corn and soybean at their early establishment stages, but were not necessary in oat's early establishment because the most abundant weed species in this experiment site were summer annuals, whose emergence and establishment are synchronized with corn and soybean. Planting oat and red clover after soybean (in the 3-year rotation), instead of circling back to corn (as in the 2-year rotation), disrupted life cycles of those summer annual weeds. An extended disruption was also imposed in the 4-year rotation with the oat/alfalfa intercrop in year three and established alfalfa in year four. Frequent hay cuts severely suppressed weed species with erect stature, such as AMATA, CHEAL, and ECHCG, but did not significantly affect other species such as TAROF, SETFA, and SETLU. TAROF is a low stature weed, which was not as severely suppressed in alfalfa and oat as were AMATA, CHEAL, and ECHCG. SETFA and SETLU are clump-forming species that are less likely to be affected by harvest machinery. In oat, AMATA, CHEAL, ECHCG, SETFA, and SETLU, like most of the summer annual weeds at the experiment site, were in their early vegetative stages at oat harvest [@buhlerEmergencePersistenceSeed2001; @cordeauHowWeedsDiffer2017]. By the weed sampling dates, those weeds were physically severed once by the oat harvest combine, or twice by additional stubble clipping if the weed pressure was deemed high.   

Tolerating higher amount of weeds might increase the risk of crop damage if weeds can serve as alternative hosts to pathogens [@wislerInteractionsWeedsCultivated2005; @mohlerCropDiseasePathogens2009]. However, soybean sudden death syndrome (SDS), caused by the soil-borne pathogen *Fusarium virguliforme* [@hartmanResearchAdvancesManagement2015], had its incidence and severity reduced due to cropping system diversification within the present experiment [@leandroCroppingSystemDiversification2018]. Among the currently recognized *Fusarium virguliforme* alternative hosts that were present at the experiment site, crops, such as alfalfa and red clover are considered symptomatic while weeds such as lambsquarter and pigweed asymptomatic [@kolanderSymptomaticAsymptomaticHost2012]. Taking the findings of @kolanderSymptomaticAsymptomaticHost2012 and @leandroCroppingSystemDiversification2018 together, it is more likely that crops played more important roles than weeds in SDS outbreaks and that cropping system diversification can control the risk of SDS outbreak effectively.    


Differences in weed responses to cropping systems and management practices were more pronounced in aboveground mass than in stand density (Tables \@ref(tab:dens-indices-ct) and \@ref(tab:biom-indices-ct)), which implied that rotation significantly affected weed growth but not weed emergence. These observations matched the general pattern reported by @weisbergerDoesDiversifyingCrop2019. We attributed the observed community composition shift to the differences in crop phenology and required management practices between the warm-season crops (corn and soybean) and the cool-season crops (oat and alfalfa) [@gabaAgroecologicalWeedControl2014; @weisbergerDoesDiversifyingCrop2019]. In the present study, the magnitude of difference in sowing dates between soybean and oat seeded with red clover or alfalfa (60 days), as compared to that of corn and soybean (14 days), could be the largest contributor to reductions of weed density.  


We considered the weed management programs in the 3-year and 4-year rotations effective because the crop yields at our experiment site were comparable between rotations (Table \@ref(tab:crop-jt-ct)) and to averages for the state of Iowa and Boone County (Figure \@ref(fig:crop-bar)). In the 2-year rotation, the net saved amount of herbicide between the low and conventional herbicide regimes was 13% as soybean plots were all treated with conventional weed management practices. The mass of herbicide active ingredients was reduced further in the 3-year and 4-year rotations as corn and soybean were supplemented with oat, red clover, and alfalfa. For example, a 3-year rotation with corn under the low herbicide regime saved 42% of herbicide active ingredients as compared to the 2-year rotation with corn under conventional weed management; and the 4-year rotation with corn under low herbicide weed management saved 57% of herbicide active ingredients as compared to the 2-year rotation with corn under conventional weed management. We also considered two weed management programs for the same crop equally effective because the crop yields were not significantly different between corn weed management regimes. In the corn phase of the rotation systems, a transition from conventional to low herbicide weed management reduced the mass of herbicide active ingredients by 80% over four years because herbicide was applied in a band half of the area planted to corn. 



Weed community aboveground mass composition and individual aboveground mass responses to cropping system diversification suggested that the weed communities that were dominated by few competitive species in the corn and soybean phases of the 2-year rotation could be shifted to have more of the rarer, less aggressive species. Community shifts to rarer, less aggressive weed species were reflected in the significant differences in ecological indices between cool-season and warm-season crops. The reduction of herbicide use, especially during oat and alfalfa phases of the rotation allowed some rarer species to grow, and thus, higher species richness and lower evenness were observed in oat and alfalfa than in corn and soybean. Community evenness indices in warm-season crops were higher than those in cool-season crops because fewer weed species were found in corn and soybean. The experimental units with high evenness index values had species of similar abundance and competitiveness, such as AMATA and CHEAL. Although an even weed community is desirable because of reduced chances that one or a few species are dominantly competitive [@adeuxMitigatingCropYield2019], weed communities could also be evenly dominated by a few weed species like AMATA, with high competitiveness, high reproduction potential, and quick herbicide resistance development. Thus, careful monitoring is required.  


It is noteworthy that the relative abundance of the top seven species appeared more even in oat and alfalfa than in corn and soybean (Figure \@ref(fig:all-sp-dens-biom)). Weeds can emerge in pulses in response to changes in soil conditions (e.g., temperature and moisture), so emergence after weed control measures have been applied and any residual effects have dissipated could result in successful establishment. Among the seven most abundant species in this experiment, five were influenced more strongly by crop identity than by corn weed management (Table \@ref(tab:ind-dens-biom-jt)). This observation is consistent with previous findings that emphasized the role of crops in weed community shifts [@davisWeedSeedbankCommunity2005; @smithAssemblyWeedCommunities2007; @owenWeedSpeciesShifts2008; @friedTrajectoriesWeedCommunities2012]. 


Due to labor constraints, only eight quadrats were evaluated per experimental unit (eu), and the samples in the eight quadrats within the same eu were tallied to make one data point. By using Simpson's ecological indices, we have limited the sensitivity of the responses to sample size [@nkoaWeedAbundanceDistribution2015]. With eight quadrats randomly spaced within an eu, we sought to control for the patchiness of weed communities [@cardinaNatureConsequenceWeed1997], but the list of weed species presented in this manuscript is likely to not be exhaustive of species at the experiment site. We suggest, however, that the responses of dominant weed species, which are more agronomically important than the rarer species, were representatively assessed because the effects of spatially separated blocks on responses were non-significant. Also due to labor constraints, individual plant weight was not assessed, so we could not explore how community evenness was affected by individual plant size and whether there was any relationship or coincidence between evenness and individual plant reproductive potential.  

A community that is dominated by AMATA, CHEAL, DIGSA, ECHCG, SETFA, and SETLU is more concerning than one dominated by TAROF, as determined by the frequency that those species are regarded as problematic [@krugerGrowerViewsProblematic2009; @princeBenchmarkStudyIntroduction2012], their seedbank persistence characteristics [@buhlerEmergencePersistenceSeed2001; @davisEnvironmentalFactorsAffecting2005], and their invulnerability to the strongest control measures [@mohlerWeedEvolutionCommunity2001; @culpepperGlyphosateinducedWeedShifts2006]. Further investigation of AMATA, CHEAL, DIGSA, ECHCG, SETFA, and SETLU population dynamics, including emergence patterns, survival throughout crop season, and reproductive potentials under various cropping systems could help guide efforts to regulate the timing of their emergence, limit their growth and reproductive potentials, and eventually deplete their seedbanks. The reproductive potential of AMATA was reduced substantially in cool-season crops as compared to warm-season crops [@nguyenImpactCroppingSystemaccepted]. Taking the finding of Nguyen and Liebman with those of @gabaAgroecologicalWeedControl2014 and @weisbergerDoesDiversifyingCrop2019, it is likely that the cool-season crops in the present study served to deplete the soil seedbank by inducing seed loss through weed emergence and granivore activities [@vanderlaatPostdispersalWeedSeed2015], while reducing reproduction potential through growth suppression. As demonstrated for SETFA [@davisCroppingSystemEffects2003a], retrospective analyses applied to aggressive weed species can contribute to understanding species responses to management practices and to tailoring management tactics and timing to target them. 


Overall, we conclude that by monitoring aboveground weed communities, a track record of species aggressiveness and collective response to management is available, and thus, it could be easier to control risks of weed resurgence and outbreak. Coupling knowledge of aboveground weed communities with that of weed seedbank composition and abundance would further improve our ability to predict and manage weed communities [@forcellaWeedSeedbanksCorn1992; @menalledWeedAbovegroundSeedbank2001; @forcellaDebitingSeedbankPriorities2003; @davisWeedSeedbankCommunity2005]. 

