---
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
    number_sections: false
    extra_dependencies: ["float"]
bibliography: ecol.bib
---

Weed communities in three cropping systems suitable for the Midwestern USA were studied from 2017 through 2020 to examine how diversified cropping systems affected weed community diversity, stand density, and aboveground mass. A baseline 2-year cropping system with corn (*Zea mays* L.) and soybean (*Glycine max* (L.) Merr.) was diversified with cool-season crops, namely oat (*Avena sativa* L.), red clover (*Trifolium pratense* L.), and alfalfa (*Medicago sativa* L.) in 3-year and 4-year systems. Herbicide was not applied in cool-season crops: oat, red clover, and alfalfa. Changing weed management regime from broadcast to banded application and interrow cultivation in corn and omitting herbicide in cool-season crops of the 3-year and 4-year rotations, resulted in overall reduction of herbicide a.i mass.
The reduction in the mass of herbicide active ingredients was associated with increased weed stand density, aboveground mass, and community diversity, but did not cause crop yield loss.

The addition of the cool-season crops into the cropping system did not affect densities of emerged weeds but did affect weed growth. The dominance of aggressive weed species such as common waterhemp (*Amaranthus tuberculatus* (Moq ex DC) J.D. Sauer) and common lambsquarter (*Chenopodium album* L.) tended to be greater in corn and soybean phases of the rotations than in oat, red clover, and alfalfa.



Keywords: weed community, diversity, evenness, richness, cropping system diversification, Midwestern USA