---
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
    number_sections: false
    extra_dependencies: ["float"]
    latex_engine: lualatex
    citation_package: natbib
bibliography: ecol.bib
natbiboptions: round
biblatexoptions:
  - sortcites = true
  - sorting = nyt
  - backend = biber
  - maxcitenames = 2
csl: apa-no-ampersand.csl
---


The composition of weed communities found in agricultural fields is strongly affected by the types of crop grown and their attendant management practices [@mohlerWeedEvolutionCommunity2001]. The U.S. Corn Belt is dominated by monocultures and short-term rotations of corn and soybean [@centerforspatialinformationscienceandsystemsCropScapeCroplandData2021]. In response to simplified crop management customized for corn and soybean, weed communities have shifted to domination by aggressive summer annual species including common waterhemp (*Amaranthus tuberculatus* (Moq ex DC) JD Sauer), Palmer amaranth (*Amaranthus palmeri* S. Wats), giant ragweed (*Ambrosia triﬁda* L.), common lambsquarter (*Chenopodium album* L.), and woolly cupgrass (*Eriochloa villosa* (Thunb) Kunth) [@owenWeedSpeciesShifts2008; @krugerGrowerViewsProblematic2009; @reddyGlyphosateresistantCropProduction2010]. Aboveground composition of weed communities is the response of the seedbank to weather conditions, crops, and crop management practices [@legereDiversityAssemblyWeed2005; @culpepperGlyphosateinducedWeedShifts2006; @smithAssemblyWeedCommunities2007]. Improved understanding of how management practices influences weed community composition can inform weed managers whether crop losses to weed competition are likely to occur and whether the weed community is shifting toward dominance by species that are more or less aggressive toward crops [@liebmanWeedManagementNeed2001].  


Cropping system diversification strategies that are designed to reduce reliance on external inputs, including herbicides, can balance productivity, profitability, and environmental quality goals [@davisIncreasingCroppingSystem2012; @huntReducingFreshwaterToxicity2017; @huntCroppingSystemDiversity2019; @huntFossilEnergyUse2020; @tamburiniAgriculturalDiversificationPromotes2020; @bowlesLongtermEvidenceShows2020; @beillouinPositiveVariableEffects2021]. They can also increase cropping systems' overall resilience to growing environmental adversity [@bowlesLongtermEvidenceShows2020] and can be effective in suppressing weeds [@weisbergerDoesDiversifyingCrop2019]. Increased crop species richness within crop sequences coupled with diversification of management practices applied to maximize crop and minimize weed resource acquisition, are expected to challenge weeds with large sets of stress and mortality factors compared to simple cropping systems [@liebmanManyLittleHammers1997; @liebmanCropDiversificationWeed2001;  @westermanAreManyLittle2005]. Nonetheless, few studies have examined weed community composition in rotations with crop species other than corn (*Zea mays* L.), soybean (*Glycine max* (L.) Merr.), and wheat (*Triticum aestivum* L.), especially in fully phased settings, in which all crop phases within a rotation are present each year to control for year to year variations in weather conditions and management efficacy [@payneDesignAnalysisLong2015]. @davisWeedSeedbankCommunity2005 studied weed aboveground and underground community shifts in four row-crop systems under four combinations of weed management and tillage regimes and found a strong negative relationship between crop yield and weed diversity, density, and total biomass; individual responses of only common waterhemp and common lambsquarter were reported. @smithAssemblyWeedCommunities2007 compared a monoculture of corn with 2-year and 3-year rotations of corn with soybean, and winter wheat, with or without cover crops and found that crop rotation and diversity had weak effects on weed community composition, whereas the cover crop in a particular rotation played an important role in weed species diversity. Increased reliance on glyphosate-based weed management has caused weed floras to shift to dominance by hard-to-control species [@owenWeedSpeciesShifts2008], but it is unclear whether reduction in herbicide use would cause the same problem.  

A more diverse weed community can be less competitive toward crops and weed seedbank diversity can be used as an indicator of cropping system sustainability [@storkeyWhatGoodWeed2018]. @liebmanWeedSeedbankDiversity2021 provided empirical evidence to support the hypothesis that seedbank diversity could be used as an indicator of cropping system sustainability as proposed by @storkeyWhatGoodWeed2018. Weed community diversity is the combination of two indices. The community evenness index ranges from 0 to 1, with higher values indicating higher evenness [@alataloProblemsMeasurementEvenness1981]. The species richness index is a count of the number of species observed. The presence of rare species in low abundance decreases the overall evenness of a weed community [@pielouInterpretationEcologicalData1984; @stirlingEmpiricalRelationshipsSpecies2001]. Studying all three indices, i.e., diversity, evenness, and richness, generates a more complete description of a community than any one of the indices [@morrisChoosingUsingDiversity2014]. 


This study was pursued to address the current gap of information concerning weed community density and aboveground mass responses to the filtering effects of different crop and weed management programs [@ryanManagementFiltersSpecies2010; @friedTrajectoriesWeedCommunities2012]. We studied three different cropping systems suitable for the US Corn Belt. The baseline system was a conventional corn - soybean system (2-year rotation with broadcast herbicide for weed control). We diversified that baseline system with oat (*Avena sativa* L.), red clover (*Trifolium pratense* L.), and alfalfa (*Medicago sativa* L.). Conventional broadcast herbicide and reduced herbicide management regimes were applied in a split-plot manner to corn phases of the three rotations. We hypothesized that diversified cropping systems, with reduced use of chemical herbicides, would provide weed control equal in effectiveness to the conventional approaches applied in the 2-year corn and soybean system. We assessed weed control efficacy by measuring weed aboveground mass and population densities. Additionally, we measured crop yields, positing that differences in weed aboveground mass and density could be reflected in differences in crop yields. Next, we hypothesized that the weed communities in the more diverse cropping systems would be more diverse, more even, and more species-rich than those in the 2-year corn and soybean system, reflecting a broader range of crop species and their attendant management practices in the more diverse rotations. Finally, we hypothesized that including oat, red clover, and alfalfa in rotations with corn and soybean would reduce the density and aboveground mass of noxious weed species in corn and soybean when the rotations cycles returned to corn and soybean.

